[[bin]]
name = "INN2"
path = "Source/Library.rs"

[dependencies]
clap = { features = ["derive"], version = "4.5.1" }
tokio = { features = ["full"], version = "1.36.0" }
walkdir = "2.5.0"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "INN2"
description = "🍺 INN2 lets you execute parallel commands in multiple directories."
license = "MIT"
name = "inn2"
repository = "https://github.com/NikolaRHristov/INN2.git"
version = "0.0.2"
edition = "2021"
