[package]
name = "innkeeper"
version = "0.0.2"
description = "Inn is a shell script to execute commmands in multiple directories."
license = "MIT"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
