[package]
name = "innkeeper"
version = "0.0.10"
description = "🍺 Inn is a tiny Rust utility that lets execute commands in different directories."
license = "MIT"
default-run = "inn"
repository = "https://github.com/NikolaRHristov/Inn.git"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
walkdir = { version = "2.4.0" }
rayon = { version = "1.8.1" }
crossbeam = { version = "0.8.4" }
toml = "0.8.8"

[lib]
name = "inn"
path = "Source/Library/main.rs"

[[bin]]
name = "inn"
path = "Source/Binary/inn.rs"

[[bin]]
name = "innkeeper"
path = "Source/Binary/innkeeper.rs"
