[package]
name = "innkeeper"
version = "0.0.6"
description = "🍺 Inn is a little Rust utility that lets execute commands in multiple directories."
license = "MIT"
default-run = "inn"

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
walkdir = { version = "2.3.3" }
rayon = { version = "1.7.0" }
crossbeam = { version = "0.8.2" }

[lib]
name = "inn"
path = "src/lib/main.rs"

[[bin]]
name = "inn"
path = "src/bin/inn.rs"

[[bin]]
name = "innkeeper"
path = "src/bin/innkeeper.rs"
