[package]
name = "innkeeper"
version = "0.0.4"
description = "Inn is a shell script that allows you to execute commmands in different directories."
license = "MIT"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
walkdir = { version = "2.3.2" }
rayon = { version = "1.6.1" }
crossbeam = { version = "0.8.2" }

[[bin]]
name = "inn"
path = "src/main.rs"
