[[bin]]
name = "Inn"
path = "Source/Function/Binary/Inn.rs"

[[bin]]
name = "Innkeeper"
path = "Source/Function/Binary/Innkeeper.rs"

[dependencies]
clap = { features = ["derive"], version = "4.5.1" }
crossbeam = { version = "0.8.4" }
rayon = { version = "1.9.0" }
walkdir = "2.4.0"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Inn"
description = "🍺 Innkeeper is a command-line tool designed to execute a specified command in all directories that match a certain pattern within a given root directory. It provides flexibility and efficiency in running commands across multiple directories with customizable patterns."
license = "MIT"
name = "innkeeper"
repository = "https://github.com/NikolaRHristov/Inn.git"
version = "0.0.16"
