[package]
name = "innkeeper"
version = "0.0.11"
description = "🍺 Inn is a tiny Rust utility that lets execute commands in different directories."
license = "MIT"
default-run = "inn"
repository = "https://github.com/NikolaRHristov/Inn.git"
autobins = false
autobenches = false
autotests = false
autoexamples = false

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
walkdir = { version = "2.4.0" }
rayon = { version = "1.8.1" }
crossbeam = { version = "0.8.4" }
toml = "0.8.10"

[[bin]]
name = "inn"
path = "src/function/binary/inn.rs"

[[bin]]
name = "innkeeper"
path = "src/function/binary/innkeeper.rs"
