[[bin]]
name = "Inn"
path = "Source/Fn/Binary/Inn.rs"

[[bin]]
name = "Innkeeper"
path = "Source/Fn/Binary/Innkeeper.rs"

[dependencies]
clap = { features = ["derive"], version = "4.5.1" }
tokio = { features = ["full"], version = "1.36.0" }
walkdir = "2.4.0"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Inn"
description = "🍺 Inn lets you execute parallel commands in multiple directories."
license = "MIT"
name = "innkeeper"
repository = "https://github.com/NikolaRHristov/Inn.git"
version = "0.1.3"
edition = "2021"
