[[bin]]
name = "Inn"
path = "Source/Library.rs"

[[bin]]
name = "Innkeeper"
path = "Source/Library.rs"

[dependencies]
clap = { features = ["derive"], version = "4.5.3" }
tokio = { features = ["full"], version = "1.36.0" }
walkdir = "2.5.0"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Inn"
description = "🍺 Run Command."
license = "MIT"
name = "innkeeper"
repository = "HTTPS://GitHub.Com/NikolaRHristov/Inn.git"
version = "0.1.8"
edition = "2021"
