[package]
name = "innkeeper"
version = "0.0.9"
description = "🍺 Inn is a little Rust utility that lets execute commands in different directories."
license = "MIT"
default-run = "inn"
repository = "https://github.com/Lightrix/innkeeper.git"

[build]
target-dir = "Target"

[dependencies]
clap = { version = "4.3.22", features = ["derive"] }
walkdir = { version = "2.3.3" }
rayon = { version = "1.7.0" }
crossbeam = { version = "0.8.2" }
toml = "0.7.6"

[lib]
name = "inn"
path = "Source/Library/main.rs"

[[bin]]
name = "inn"
path = "Source/Binary/inn.rs"

[[bin]]
name = "innkeeper"
path = "Source/Binary/innkeeper.rs"
