[package]
name = "innkeeper"
version = "0.0.14"
description = "🍺 Inn is a tiny Rust utility that lets execute commands in different directories."
license = "MIT"
default-run = "Inn"
repository = "https://github.com/NikolaRHristov/Inn.git"
autobins = false
autobenches = false
autotests = false
autoexamples = false

[[bin]]
name = "Inn"
path = "Source/Function/Binary/Inn.rs"

[[bin]]
name = "Innkeeper"
path = "Source/Function/Binary/Innkeeper.rs"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
crossbeam = { version = "0.8.4" }
rayon = { version = "1.9.0" }
walkdir = { version = "2.4.0" }
