name: Inn

concurrency:
    group: inn-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_call:

jobs:
    build:
        strategy:
            matrix:
                toolchain: [stable, nightly]
                platform: [windows-latest, ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.platform }}

        steps:
            - uses: actions/checkout@v3.5.0
            - uses: actions-rs/toolchain@v1.0.7
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}

            - uses: actions/cache@v3.3.1
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key:
                      ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.toml') }}
            - uses: actions-rs/cargo@v1.0.3
              with:
                  command: build
                  args:
                      --release --all-features --manifest-path ./Cargo.toml

            - uses: actions/upload-artifact@v3.1.2
              with:
                  name: .-inn-${{ matrix.platform }}-target
                  path: ./target

            - run: |
                  git add bench/
                  git add 
                  git config --global user.name 'Bench'
                  git config --global user.email 'bench@nikolahristov.tech'
                  git commit -m "Auto Bench $(git log -1 --pretty=%h) $(git log -1 --pretty=%B)"
                  git push
