name: Inn

concurrency:
    group: inn-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_call:

jobs:
    build:
        strategy:
            matrix:
                toolchain: [stable, nightly]
                platform: [windows-latest, ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.platform }}
        continue-on-error: true

        steps:
            - uses: actions/checkout@v3.5.3
            - uses: actions-rs/toolchain@v1.0.7
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}

            - uses: actions/cache@v3.3.1
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                      Target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.toml') }}
            - uses: actions-rs/cargo@v1.0.3
              with:
                  command: build
                  args: --release --all-features --manifest-path ./Cargo.toml

            - uses: actions/upload-artifact@v3.1.2
              with:
                  name: .-inn-${{ matrix.platform }}-target
                  path: ./Target

            - run: |
                  git add Target
                  git config --global user.name 'Inn'
                  git config --global user.email 'inn@lightrix.help'
                  git commit -m "Inn Release $(git log -1 --pretty=%h) $(git log -1 --pretty=%B)"
                  git pull && git push
